import { Project, ActivityEvent } from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-1",
    slug: "promptpulse",
    title: "PromptPulse AI",
    tagline: "Real-time analytics and cost optimization for LLM API calls in production.",
    description: "PromptPulse tracks latency, token burn rate, prompt versioning, and cache hits for OpenAI, Claude, and Gemini APIs in real time with zero latency overhead.",
    url: "https://promptpulse.dev",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=promptpulse",
    screenshot_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    category: "AI & ML",
    submitter_email: "alex@promptpulse.dev",
    total_amount_usd: 245.0,
    current_rank: 1,
    previous_rank: 1,
    all_time_clicks: 1420,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "proj-2",
    slug: "typemagic",
    title: "TypeMagic Form Builder",
    tagline: "Notion-style conversational forms with AI qualification & instant webhook triggers.",
    description: "Build beautiful interactive forms in minutes. Increase lead conversion by 3x with dynamic question branching and instant Zapier/Slack sync.",
    url: "https://typemagic.io",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=typemagic",
    screenshot_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
    category: "SaaS",
    submitter_email: "sarah@typemagic.io",
    total_amount_usd: 190.0,
    current_rank: 2,
    previous_rank: 2,
    all_time_clicks: 980,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "proj-3",
    slug: "screenflow-pro",
    title: "ScreenFlow Pro",
    tagline: "Turn raw screen recordings into studio-grade product demos with auto-zoom and captions.",
    description: "Record your screen and let AI generate smooth zooms, spotlight cursor effects, studio audio cleanup, and animated subtitles automatically.",
    url: "https://screenflowpro.app",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=screenflow",
    screenshot_url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80",
    category: "Design & Creative",
    submitter_email: "dev@screenflowpro.app",
    total_amount_usd: 140.0,
    current_rank: 3,
    previous_rank: 4,
    all_time_clicks: 740,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "proj-4",
    slug: "cronmonitor",
    title: "CronSentry",
    tagline: "Dead-simple heartbeat and cron job monitoring with Telegram and Discord alerts.",
    description: "Never suffer silent cron failures again. Ping our endpoint on scheduled tasks; if we don't hear back within your threshold, you get alerted in seconds.",
    url: "https://cronsentry.dev",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=cronsentry",
    screenshot_url: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&auto=format&fit=crop&q=80",
    category: "Developer Tools",
    submitter_email: "vikram@cronsentry.dev",
    total_amount_usd: 115.0,
    current_rank: 4,
    previous_rank: 3,
    all_time_clicks: 610,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: "proj-5",
    slug: "invoiceninja-ai",
    title: "Lumina Invoice",
    tagline: "Micro-SaaS billing & recurring invoice generator with built-in UPI QR code generator.",
    description: "Effortless cross-border invoices for indie freelancers and micro-agencies with instant PDF export and automated payment reminders.",
    url: "https://luminainvoice.com",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=luminainvoice",
    screenshot_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop&q=80",
    category: "Finance & Crypto",
    submitter_email: "rahul@luminainvoice.com",
    total_amount_usd: 90.0,
    current_rank: 5,
    previous_rank: 5,
    all_time_clicks: 530,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 15).toISOString(),
  },
  {
    id: "proj-6",
    slug: "seospy",
    title: "KeyRank Spy",
    tagline: "Track competitor organic keywords and backlink changes daily without enterprise pricing.",
    description: "Get weekly digests of keywords your indie competitors are newly ranking for, along with keyword difficulty opportunities.",
    url: "https://keyrankspy.com",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=keyrankspy",
    screenshot_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    category: "Marketing & SEO",
    submitter_email: "elena@keyrankspy.com",
    total_amount_usd: 75.0,
    current_rank: 6,
    previous_rank: 6,
    all_time_clicks: 420,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
  {
    id: "proj-7",
    slug: "habitsync",
    title: "HabitSync macOS",
    tagline: "Minimalist menu bar habit tracker that syncs with Apple Health & GitHub activity.",
    description: "A gorgeous native macOS app that sits discreetly in your menu bar, helping developers build daily deep work and wellness habits.",
    url: "https://habitsync.app",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=habitsync",
    screenshot_url: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&auto=format&fit=crop&q=80",
    category: "Productivity",
    submitter_email: "lucas@habitsync.app",
    total_amount_usd: 55.0,
    current_rank: 7,
    previous_rank: 8,
    all_time_clicks: 340,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: "proj-8",
    slug: "dockeready",
    title: "DockReady CLI",
    tagline: "Generate optimized multi-stage Dockerfiles and compose setups for any stack with one command.",
    description: "Scan your repository and generate battle-tested, secure, and caching-optimized Docker configs for Next.js, Go, Rust, and Python.",
    url: "https://dockready.io",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=dockready",
    screenshot_url: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop&q=80",
    category: "Developer Tools",
    submitter_email: "marcus@dockready.io",
    total_amount_usd: 40.0,
    current_rank: 8,
    previous_rank: 7,
    all_time_clicks: 290,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 30).toISOString(),
  },
  {
    id: "proj-9",
    slug: "audiogram-gen",
    title: "AudioWave Viral",
    tagline: "Convert podcast audio snippets into hypnotic animated waveform video shorts for TikTok.",
    description: "Automate social video clips with dynamic audio waveforms, animated text overlays, and AI voice transcriptions.",
    url: "https://audiowaveviral.com",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=audiowave",
    screenshot_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&auto=format&fit=crop&q=80",
    category: "Design & Creative",
    submitter_email: "claire@audiowave.com",
    total_amount_usd: 30.0,
    current_rank: 9,
    previous_rank: 9,
    all_time_clicks: 210,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: "proj-10",
    slug: "sqlite-cloud-sync",
    title: "LiteSync Cloud",
    tagline: "Bi-directional SQLite replication over WebSockets for local-first web applications.",
    description: "Build snappy offline-first web apps that sync seamlessly with your backend cloud DB with automatic CRDT conflict resolution.",
    url: "https://litesync.dev",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=litesync",
    screenshot_url: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format&fit=crop&q=80",
    category: "Developer Tools",
    submitter_email: "dev@litesync.dev",
    total_amount_usd: 25.0,
    current_rank: 10,
    previous_rank: 10,
    all_time_clicks: 180,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 40).toISOString(),
  },
  {
    id: "proj-11",
    slug: "postpilot-x",
    title: "PostPilot X",
    tagline: "Schedule Twitter / X threads and analyze engagement spikes with smart reposting.",
    description: "Smart queueing for tech creators on X. Automatically quote-tweet your best performing posts when your audience is most active.",
    url: "https://postpilot.app",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=postpilot",
    screenshot_url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&auto=format&fit=crop&q=80",
    category: "Marketing & SEO",
    submitter_email: "jordan@postpilot.app",
    total_amount_usd: 20.0,
    current_rank: 11,
    previous_rank: 11,
    all_time_clicks: 150,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: "proj-12",
    slug: "git-bounty",
    title: "GitBounty.dev",
    tagline: "Post micro-bounties for open source GitHub issues and get PRs merged in 48 hours.",
    description: "Attach cash bounties to your repository issues. Developers solve issues, you review the PR, and payouts trigger automatically via Stripe or Crypto.",
    url: "https://gitbounty.dev",
    favicon_url: "https://api.dicebear.com/7.x/identicon/svg?seed=gitbounty",
    screenshot_url: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&auto=format&fit=crop&q=80",
    category: "Developer Tools",
    submitter_email: "admin@gitbounty.dev",
    total_amount_usd: 15.0,
    current_rank: 12,
    previous_rank: 12,
    all_time_clicks: 115,
    is_verified: true,
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 25).toISOString(),
  },
];

export const INITIAL_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-1",
    type: "outbid_crown",
    project_title: "PromptPulse AI",
    project_slug: "promptpulse",
    amount_usd: 55.0,
    old_rank: 2,
    new_rank: 1,
    outbid_project_title: "TypeMagic Form Builder",
    timestamp: "2 hours ago",
  },
  {
    id: "act-2",
    type: "rank_jump",
    project_title: "ScreenFlow Pro",
    project_slug: "screenflow-pro",
    amount_usd: 40.0,
    old_rank: 4,
    new_rank: 3,
    outbid_project_title: "CronSentry",
    timestamp: "4 hours ago",
  },
  {
    id: "act-3",
    type: "boost_bid",
    project_title: "HabitSync macOS",
    project_slug: "habitsync",
    amount_usd: 25.0,
    old_rank: 8,
    new_rank: 7,
    timestamp: "6 hours ago",
  },
  {
    id: "act-4",
    type: "new_project",
    project_title: "Audiowave Viral",
    project_slug: "audiogram-gen",
    amount_usd: 30.0,
    new_rank: 9,
    timestamp: "1 day ago",
  },
];
